Repository shardeum/json-rpc-server, pull requests merged in 2025-03, with the labels that each got.

#136 SHARD-1961: fixes for newHeads
  src/api.ts
  src/server.ts
  src/websocket/index.ts
  src/websocket/log_server.ts
  src/websocket/newhead_server.ts
  test/unit/websocket/index.test.ts
Labels: Review effort 4/5

#140 SHARD-2039: Return empty array from eth_accounts instead of hardcoded address
  src/api.ts
Labels: Review effort 1/5

#139 SHARD-2024: Fix incorrect transaction index
  src/api.ts
  src/eth-handlers/eth_getTransactionByBlockHashAndIndex.ts
  src/eth-handlers/eth_getTransactionByBlockNumberAndIndex.ts
  test/unit/eth-handlers/eth_getTransactionByBlockHashAndIndex.test.ts
  test/unit/eth-handlers/eth_getTransactionByBlockNumberAndIndex.test.ts
Labels: Review effort 2/5

#143 SHARD-2024: Add typing to extracted methods
  src/eth-handlers/eth_getTransactionByBlockHashAndIndex.ts
  src/eth-handlers/eth_getTransactionByBlockNumberAndIndex.ts
Labels: Review effort 2/5

#142 SHARD-2035: fix leading 0 in gasUsed
  src/external/Collector.ts
  src/utils/gasCalculator.ts
  test/unit/utils/gasCalculator.test.ts
Labels: Review effort 2/5

#144 fix: update readme to better explain how to enable the new request logging
  README.md
Labels: Review effort 1/5
